version: 1.0.{build}

image:
- Ubuntu
- Visual Studio 2022

init:
- sh: sudo apt update && sudo apt install -y xorg-dev mesa-common-dev libgl-dev

clone_script:
- sh: git clone https://github.com/DezlowNG/OneiroEngine --recursive && cd OneiroEngine
- cmd: git clone https://github.com/DezlowNG/OneiroEngine --recursive && cd OneiroEngine

build_script:
- sh: cmake SandBox/ -DCMAKE_CXX23_EXTENSION_COMPILE_OPTION="-std=gnu++2a" && make
- cmd: cmake --build SandBox/
